name: remote_notification_reteno_service
description: Reteno remote notification service module
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  async: ^2.13.0
  common_result:
    git:
      url: git@github.com:nove8/fl-common-result.git
      ref: 4.0.0
  remote_notification_service:
    git:
      url: git@github.com:nove8/fl-services.git
      path: remote_notification
      ref: remote_notification-v2.0.0
  reteno_plugin: ^1.9.1
  rxdart: ^0.28.0

dev_dependencies:
  common_package:
    git:
      url: git@github.com:nove8/fl-common-package.git
      ref: 4.2.0
