import 'package:async/async.dart';

/// A service interface for retrieving package information.
abstract interface class PackageInfoService {
  /// The application version.
  ///
  /// Returns the version string of the application.
  /// This is typically the user-facing version number.
  Future<Result<String>> get appVersion;

  /// The application name.
  ///
  /// Returns the display name of the application as shown to users.
  Future<Result<String>> get appName;

  /// The package name.
  ///
  /// - `bundleIdentifier` on iOS.
  ///   Defined in the product target in xcode.
  /// - `packageName` on Android.
  ///   Defined in `build.gradle` as `applicationId`.
  /// - `package_name` from `version.json` on Web.
  ///   Generated by Flutter.
  Future<Result<String>> get packageName;

  /// The package version.
  /// Generated from the version in `pubspec.yaml`.
  ///
  /// - `CFBundleShortVersionString` on iOS.
  /// - `versionName` on Android.
  /// - `version` from `version.json` on Web.
  Future<Result<String>> get packageVersion;
}
