name: share_service
description: Share service module
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.4

dependencies:
  async: ^2.13.1
  share_plus: ^12.0.2

  common_result:
    git:
      url: git@github.com:nove8/fl-common-result.git
      ref: 4.0.0

dev_dependencies:
  common_package:
    git:
      url: git@github.com:nove8/fl-common-package.git
      ref: 4.2.0
